### ISSUE TITLE
Relay LED indicator turns on by itself 

### ISSUE THREAD

**Issue by ifurnadjiev** [romasku/tuya-zigbee-switch#38]
I have MOES 2 gang switch, flashed with 1.0.13 firmware (Moes-2-gang-ED). The LED indicator is configured to be the "same" as the relay state. Sometimes, without touching the switch, both relay LED indicators turn on, but the switch is off. Toggle the switch on and off make the indicator LED in sync with relay again.

Are there any specific case, where the LED indicators turn on by themself?

**Comment by romasku** [comment]
Hi,
It is possible that when the EndDevice reconnects to the Zigbee network, it briefly goes into "Looking for network" mode and starts flashing LEDs. Then, after reconnect, it (probably) forgets to restore the LED state. I'll check it.

**Comment by ifurnadjiev** [comment]
Thank you. That's happening with several of my MOES switches - single and double. My Zigbee network is rock solid. That's the only issue I have with your firmware. Once per 3-4 days one of the switches turns it's LED indicator itself.

**Comment by ifurnadjiev** [comment]
It happened again this morning with two of my MOES single gang switches. Appreciate your fix.

**Comment by romasku** [comment]
Sorry, I'll look into it over the weekend. Unfortunately, I don't have time at the moment.

**Comment by romasku** [comment]
Hi, I've just released version 1.0.14, which should fix your issue.

I wasn't able to fully reproduce the problem, but I made a change so the device will automatically correct the LED state if it goes out of sync.

**Comment by ifurnadjiev** [comment]
Thank you very much. Really appreciate it.

**Comment by ifurnadjiev** [comment]
After two weeks of testing I can confirm that the issue has been resolved.

**Comment by ifurnadjiev** [comment]
After installing 1.1.0 firmware (from 1.0.21) the issue is back. The LED indicator of end device (MOES single or double switch) turn on themself. Maybe by mistake you removed the fix during the refactoring.

**Comment by ifurnadjiev** [comment]
@romasku Could you please check it?  The issue has been fixed in 1.0.14 firmware.

**Comment by romasku** [comment]
I'll check, thank you for reporting it.

**Comment by ifurnadjiev** [comment]
@romasku Is this issue fixed in 1.1.1 version?

**Comment by andrei-lazarov** [comment]
Not sure. Please update and let us know if it persists.

**Comment by ifurnadjiev** [comment]
By reading the code I don't see a particular fix. That's why I'm asking.

**Comment by andrei-lazarov** [comment]
This issue was not particularly addressed, but Romasku fixed a severe memory alignment bug - which may or may not be related.

**Comment by ifurnadjiev** [comment]
Probably is not, as the original issue (described in the opening of the thread) was a missing LED indicator synchronization after the end device looking for network.

**Comment by romasku** [comment]
Sorry, not fixed yet

**Comment by ifurnadjiev** [comment]
When you have 20+ wall switches, it's anoing to see every morning several of them with LED indicator out of sync. I really appreciate your fix.

**Comment by ifurnadjiev** [comment]
@romasku Sorry for nagging, but could you please address this issue. Everything is working fine for me, but this issue makes me crazy.

**Comment by romasku** [comment]
Just pushed the fix an hour ago; I think I'll do a release today.

**Comment by ifurnadjiev** [comment]
I'm really thankful.

**Comment by romasku** [comment]
Just published 1.1.2, please try it.

**Comment by ifurnadjiev** [comment]
Running 1.1.2 for two days - no issues so far. Thanks for fixing it.
